name: Publish PlatformIO

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Create Release"]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO CLI
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Publish to PlatformIO Registry
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
      run: |
        pio package publish --type library --no-interactive --owner sidcha
